### ISSUE TITLE
No output of starred RSS feeds

### ISSUE THREAD

**Issue by maitrenageur** [rogierlommers/miniflux-exporter#3]
Hello,

I tried several times in several combinations, but is doesn't run. I get always the error:

INFO[0000] skipping opml export (see -help for more info)
INFO[0000] skipping export of bookmarks/starred entries (see -help for more info) 
-bash: JUB+y: Command not found.

I used the following line as example:

`./miniflux-exporter -user username -pass password -host http://127.0.0.1:62345 -output-opml /test/miniflux-opml.xml`

Any ideas?

Thank you

**Comment by rogierlommers** [comment]
If you do this: `./miniflux-exporter -help`, what do you get?

**Comment by maitrenageur** [comment]
Yes, the directory exists and the write permissions are available. The output of `./miniflux-exporter -help` is:

````
Usage of ./miniflux-exporter:
  -host string
    	miniflux hostname, f.e. http://localhost:8080 (default "http://localhost:8080")
  -output-bookmarks string
    	output filename, f.e. /tmp/bookmarks.txt
  -output-opml string
    	output filename, f.e. /tmp/opml.xml
  -pass string
    	miniflux password
  -s	if flag -s is provided, the happy-flow won't display any output
  -user string
    	miniflux username
````

**Comment by maitrenageur** [comment]
I have seen in Miniflux2 the API endpoint is `http://127.0.0.1/v1/`. Has for miniflux-exporter the `v1` a special meaning?

**Comment by maitrenageur** [comment]
I found my mistake. I used a password with special characters. This don't like miniflux-exporter.

**Comment by rogierlommers** [comment]
Thanks for the comment, @maitrenageur . I think you need to escape the special characters and/or put them around quotes. Anyhow, solved :).
