### ISSUE TITLE
Add export of starred URLs to RSS file

### ISSUE THREAD

**Issue by maitrenageur** [rogierlommers/miniflux-exporter#4]
Hi,

It is possible to export starred URLs as RSS feed file?
It would be helpful to integrate it in other feed reader again, especially in my document management system DEVONthink.

Thank you

**Comment by rogierlommers** [comment]
I can add that, but is it okay to output as a (rss) file? or do you need a running webserver? I prefer just a simple CLI application, so I don't want to embed a http server in it.

**Comment by maitrenageur** [comment]
I need only the rss file, that i can storage on my own webserver. This rss file should have the format, that i can use  a standard feed reader. And thank you for your support.

**Comment by rogierlommers** [comment]
Keep an eye on this branch: https://github.com/rogierlommers/miniflux-exporter/tree/feature/Add-export-of-starred-URLs-to-RSS-file

**Comment by rogierlommers** [comment]
Here you are: https://github.com/rogierlommers/miniflux-exporter/releases/tag/5

**Comment by maitrenageur** [comment]
Thank you very much. I think, this export possibility is helpful for other users too.
