### ISSUE TITLE
Quit after backup

### ISSUE THREAD

**Issue by austinliuu** [rogierlommers/miniflux-exporter#7]
I use the -s flag to backup the miniflux docker instance but the binary would keep running after backup is done. Is it possible to make it quit quietly after backup is done?

**Comment by rogierlommers** [comment]
Hey @austinliuu , what exactly do you mean? The miniflux-exporter app doesn't bind to a port or keeps running. When the export is successfully made, then it quits. Can you elaborate a bit more how and when you run the binary?

**Comment by austinliuu** [comment]
When I try to run the binary it will hang there after the export is done 
![image](https://user-images.githubusercontent.com/30453289/216785606-cd1e4bc1-e329-4077-b8f8-064108d8c98f.png)
