### ISSUE TITLE
Output bookmarks broken

### ISSUE THREAD

**Issue by wogong** [rogierlommers/miniflux-exporter#8]
Command: `./miniflux-exporter -s -user xx -pass xx -host http://localhost:8080 -output-bookmarks "./bookmarks.xml"`
Expected: Generate file `bookmarks.xml`
Got: `ERRO[0007] Get http://localhost:8080/v1/entries?limit=0&offset=0: EOF` and miniflux exited with `miniflux_miniflux_1 exited with code 137`.

The `-output-opml` option worked as expected.
I have 203 starred items.

**Comment by rogierlommers** [comment]
Hey @wogong , I cannot reproduce your issue.
However I did see some changes in the Miniflux repo; I just created a new release.
Can you try this new binary?

https://github.com/rogierlommers/miniflux-exporter/releases/tag/6

**Comment by wogong** [comment]
Sorry for the late reply.
Tried again and problem remains.
I doubt if I have too many starred items (538).

**Comment by rogierlommers** [comment]
Hey @wogong , can you please try this release?
https://github.com/rogierlommers/miniflux-exporter/releases/tag/8

And please add the `-v`-flag, which outputs a lot of debugging info.

**Comment by wogong** [comment]
I migrated to FreshRSS for my needs. Thank you for your assistance and efforts nonetheless.
